### ISSUE TITLE
[Question] Status of project

### ISSUE THREAD

**Issue by AStoker** [jamesgeorgedunn/Modest-Grid#2]
Considering using Modest Grid, but there doesn't seem to be a lot of activity (PR from 2015 still left untouched). What is the current status of this project? Is there future development/enhancements planned?

**Comment by jamesgeorgedunn** [comment]
There's been quite a lot of improvements but they've been mainly for in-house use at the software development company I work for.

I haven't had much time to work on many open source projects I'm afraid.

**Comment by AStoker** [comment]
:+1: Thanks for the info!

**Comment by WiredUK** [comment]
Come on James, pull your finger out mate! :P
